#syntax=docker-compose/docker-compose:3
#link::https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3"

services:

  fastpy:
    image: python:alpine
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - type: volume
        source: database
        target: /database
        volume:
          nocopy: true
    command: ["echo", "Fastpy is enable!"]

volumes:
  database:
